import { DEFAULT_APP_CONFIG } from "../../../AppConfig";
import { PresetLayoutType } from "../../../core/layouts/layoutEngineTypes";
import { Graph } from "../../../core/model/Graph";
import { SceneGraph } from "../../../core/model/SceneGraph";

export const demo_URL_Shortener = () => {
  const graph = new Graph();

  // ========== NODES - Exact components from diagram ==========

  // Client (left)
  const client = graph.createNode({
    id: "Client",
    type: "storyCard",
    position: { x: -600, y: 0, z: 0 },
    userData: {
      title: "Client",
      description:
        "The end-user's browser or application that sends a request for a shortened URL and receives the redirect response.",
      tags: ["client", "browser", "user"],
    },
  });

  // Edge/CDN (optional) (center-left)
  const edgeCdn = graph.createNode({
    id: "Edge/CDN (optional)",
    type: "storyCard",
    position: { x: -200, y: 0, z: 0 },
    userData: {
      title: "Edge/CDN (optional)",
      description:
        "An optional Content Delivery Network or edge server layer. Its purpose is to provide geographic distribution and potentially cache redirect responses closer to the user, reducing latency.",
      tags: ["edge", "cdn", "caching", "geographic distribution"],
    },
  });

  // Redirect Service (center)
  const redirectService = graph.createNode({
    id: "Redirect Service",
    type: "storyCard",
    position: { x: 200, y: 0, z: 0 },
    userData: {
      title: "Redirect Service",
      description:
        "The central application logic responsible for handling short URL redirect requests. It orchestrates the lookup of long URLs, manages caching, and issues HTTP redirect responses.",
      tags: ["redirect", "service", "core", "hot path"],
    },
  });

  // Redis Cache (top-right)
  const redisCache = graph.createNode({
    id: "Redis Cache",
    type: "storyCard",
    position: { x: 400, y: -300, z: 0 },
    userData: {
      title: "Redis Cache",
      description:
        'A fast, in-memory data store used as a caching layer. It stores frequently accessed short code to long URL mappings to accelerate the redirect process (the "hot path").',
      tags: ["redis", "cache", "hot path", "in-memory"],
    },
  });

  // KV Shard (bottom-right)
  const kvShard = graph.createNode({
    id: "KV Shard",
    type: "storyCard",
    position: { x: 400, y: 300, z: 0 },
    userData: {
      title: "KV Shard",
      description:
        "A Key-Value store, likely sharded for scalability and fault tolerance, serving as the persistent storage for all short code to long URL mappings and associated metadata (flags).",
      tags: ["database", "kv store", "sharding", "persistent storage"],
    },
  });

  // Event Queue (bottom-right, below KV Shard)
  const eventQueue = graph.createNode({
    id: "Event Queue",
    type: "storyCard",
    position: { x: 400, y: 500, z: 0 },
    userData: {
      title: "Event Queue",
      description:
        'An asynchronous messaging queue used to process events, specifically "click events" generated by the Redirect Service, without blocking the main redirect flow.',
      tags: ["queue", "events", "analytics", "async processing"],
    },
  });

  // ========== EDGES - Exact flows from diagram ==========

  // Synchronous flows (solid lines)

  // Client → Edge/CDN: GET /{code}
  graph.createEdge(client.getId(), edgeCdn.getId(), {
    type: "redirect",
    label: "GET /{code}",
  });

  // Edge/CDN → Redirect Service: forward (or cache miss)
  graph.createEdge(edgeCdn.getId(), redirectService.getId(), {
    type: "redirect",
    label: "forward (or cache miss)",
  });

  // Synchronous flows (solid lines)

  // Client → Edge/CDN: GET /{code}
  graph.createEdgeIfMissing(client.getId(), edgeCdn.getId(), {
    type: "redirect",
    label: "GET /{code}",
  });

  // Edge/CDN → Redirect Service: forward (or cache miss)
  graph.createEdgeIfMissing(edgeCdn.getId(), redirectService.getId(), {
    type: "redirect",
    label: "forward (or cache miss)",
  });

  // Redirect Service → Redis Cache: GET code
  const redirectToRedisEdge = graph.createEdgeIfMissing(
    redirectService.getId(),
    redisCache.getId(),
    {
      type: "redirect",
      label: "GET code",
    }
  );

  // Redis Cache → Redirect Service: hit: longURL or miss
  graph.createEdgeIfMissing(redisCache.getId(), redirectService.getId(), {
    type: "redirect",
    label: "hit: longURL or miss",
  });

  // Redirect Service → KV Shard: miss: read mapping
  graph.createEdgeIfMissing(redirectService.getId(), kvShard.getId(), {
    type: "redirect",
    label: "miss: read mapping",
  });

  // KV Shard → Redirect Service: longURL + flags
  graph.createEdgeIfMissing(kvShard.getId(), redirectService.getId(), {
    type: "redirect",
    label: "longURL + flags",
  });

  // Redirect Service → Edge/CDN: 302/301 + Location
  graph.createEdgeIfMissing(redirectService.getId(), edgeCdn.getId(), {
    type: "redirect",
    label: "302/301 + Location",
  });

  // Edge/CDN → Client: redirect response
  graph.createEdgeIfMissing(edgeCdn.getId(), client.getId(), {
    type: "redirect",
    label: "redirect response",
  });

  // Asynchronous flows (dashed lines)
  // Note: The graph model only allows one edge per source-target pair.
  // For the async "set hot entry" flow from Redirect Service → Redis Cache,
  // we'll store it in the existing edge's userData since we already have
  // a synchronous edge between these nodes.
  if (redirectToRedisEdge) {
    redirectToRedisEdge.getData().userData = {
      ...redirectToRedisEdge.getData().userData,
      asyncLabel: "set hot entry",
      hasAsyncFlow: true,
    };
  }

  // Redirect Service → Event Queue: click event (async)
  graph.createEdgeIfMissing(redirectService.getId(), eventQueue.getId(), {
    type: "async",
    label: "click event (async)",
  });

  const sceneGraph = new SceneGraph({
    graph,
    metadata: {
      name: "Redirect path deep dive (hot path)",
      description:
        "Figure 2 - Redirect request sequence (hot path). The diagram shows the flow of a request from a client to resolve a short URL into its original long URL and then redirect the client.",
    },
    defaultAppConfig: {
      ...DEFAULT_APP_CONFIG(),
      activeLayout: PresetLayoutType.NodePositions,
      activeView: "ReactFlow",
    },
  });

  return sceneGraph;
};
